/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AvantgardeToken } from "./AvantgardeToken";
export * as factories from "./factories";
export { AvantgardeToken__factory } from "./factories/AvantgardeToken__factory";
